### PR TITLE
Refactored missions profile

### PR DESCRIPTION
**Pull request by kennankole**
> Made changes to the missions profile 
* User's missions stay on the missions profile during the session
* Display default message on missions profile

### CODE REVIEW

**Review by Mujeeb4582 — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @kennankole 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- Gitflow is followed. :heavy_check_mark:
- PR has a good title and summary. ✔️



## Required Changes ♻️
_Kindly check below design and compare make it like Microverse requirements._
## Your Design
My partner Design
## Microverse Requirements
Required Design
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by kennankole** [comment]
Thanks, @Mujeeb4582 for the suggestions. 
However, I think we should only have one button as described [here](https://github.com/microverseinc/curriculum-react-redux/blob/main/group-project/project_space_travelers_hub.md#:~:text=There%20is%20also%20a%20button%20next%20to%20each%20mission%20that%20allows%20users%20to%20join%20the%20selected%20mission%20or%20leave%20the%20mission%20the%20user%20joined%20earlier.) 
Notice that it says a `button` and not `buttons`. Therefore, I think the other "buttion" is just do display the status of the user whether or not they are a member. 

Nonetheless, I have also seen my mistake through your review and I have rectified this as can be seen in the screencast below
[Screencast from 22-12-2022 10:35:57 WD.webm](https://user-images.githubusercontent.com/39535023/209082545-ecb65c96-fc67-47a0-8a75-efb4f26581ed.webm)


I hope this makes sense to you. 
Thank you 🙏🏿  
waiting for your response

**Comment by Mujeeb4582** [comment]
@kennankole Yes, you are right but you select the wrong button please correct that just change the button functionality. Push your changes. It can't show on my side, your new changes. 
I also watched the video, it's correct now. You did a great job but when I check it on my computer it's the same as the previous one.

**Review by Mujeeb4582 — APPROVED** [review]
Congratulations @kennankole  for resolving the merge conflict.
There is nothing else to do other than to merge the branch. 
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
 
68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966

### Cheers and Happy Coding 💯

**Pull request merged**
